import 'dart:math';

import 'package:Appetize/Preferences.dart';
import 'package:Appetize/colors.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'FrontPage.dart';
import 'globals.dart' as globals;

void main() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();

  /* DEMO ID. In the future IDs will be generated by the server. */
  if (prefs.getString('id') == null) {
    var rand = Random();
    globals.id = 'APPETIZE_ID:' + rand.nextInt(1000000).toString();
    savePreferences();
  }

  globals.id = prefs.getString('id');

  setRestaurantColors(globals.restaurants);

  SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarColor: Colors.black));
  runApp(FrontPage(globals.restaurants));
}
